#!/usr/bin/env bash
# Transfers a file from our client to a server
#
# variables
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <file_to_transfer> <remote_ip>"
    exit 1
fi

file_to_transfer="$1"
remote_ip="$2"

scp -i ~/.ssh/holberton "$file_to_transfer" ubuntu@"$remote_ip":/tmp/
